apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cicd-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 192.168.56.20:5000/backend:latest
          ports:
            - containerPort: 3000