all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: /home/vagrant/.ssh/vagrant_insecure
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
  children:
    k8s_master:
      hosts:
        ctrl1:
          ansible_host: 192.168.56.10
    k8s_workers:
      hosts:
        wk1:
          ansible_host: 192.168.56.11
        wk2:
          ansible_host: 192.168.56.12
    jenkins:
      hosts:
        cicd:
          ansible_host: 192.168.56.20







