---
- name: Install Docker Engine on Workers
  hosts: wk1,wk2
  become: yes


  vars:
    docker_users:
      - vagrant

    docker_daemon_config:
      exec-opts: ["native.cgroupdriver=systemd"]
      log-driver: "json-file"
      log-opts:
        max-size: "100m"
      storage-driver: "overlay2"


  pre_tasks:
    - name: Ensure apt cache is fresh and prereqs installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0664" 

      
    - name: Add Docker apt repository (Ubuntu/Debian)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
      when: ansible_facts['os_family'] == "Debian"


  tasks:
    - name: Install Docker Engine packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Write /etc/docker/daemon.json
      ansible.builtin.copy:
        content: "{{ docker_daemon_config | to_nice_json }}"
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: Restart Docker


    - name: Enable and Start Docker Service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes 

    - name: Add users to docker group (no sudo needed for docker)
      ansible.builtin.user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop: "{{ docker_users }}"

    - name: Enable IPv4 forwarding (useful later for K8s/networking)
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes


  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
