# update.yml
- name: System update & base tooling
  hosts: all
  become: true
  gather_facts: true

  vars:
    apt_packages:
      -curl
      -git
      -jq
      -ufw
      -apt-transport-https
      -ca-certificates
      -gnupg
      -lsb-release
      -python3
      -python3-pip
    timezone_name: Etc/UTC


  environment:
    DEBIAN_FRONTEND: noninteractive

  tasks:
    - name: Update apt cache (fast-fail with lock timeout)
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
        lockout_time: 60

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes
        lock_timeout: 60

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ apt_packages }}"
        state: present
        force_apt_get: yes
        lock_timeout: 60
        dpkg_options: "--force-confnew"

    - name: Set system timezon (preferred)
      community.general.timezone:
        name: "{{ timezone_name }}"
      ignore_errors: yes

    - name: Ensure timezone via timedatectl (fallback)
      ansible.builtin.command: "timedatectl set-timezone {{ timezone_name }}"
      changed_when: false
      when: ansible_facts.tz is not defined or ansible_facts.tz != timezone_name

    - name: Provisioning complete (timestamp)
      ansible.builtin.debug:
        msg: "[{{ ansible_date_time.date }} {{ ansible_date_time.time }}] Provisioning complete."
